name: dipassm
dependencies:
  - Python=3.7.*
  - pip=21.0.1
  - openssl=1.1.1j
  - Snakemake<6.0.0
  - drmaa=0.7.9
  - pyyaml=5.3
  - pandas=1.2.3
  - pytables=3.6.1
  - intervaltree=3.0.2
  - pulp=2.4