name: shelltools
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - wget=1.19.4
  - libssh2=1.8.0
  - openssl=1.0.2t
  - libcurl=7.64.0
  - curl=7.64.0
  - aria2=1.34.0
  - pbgzip=2016.08.04
  - zlib=1.2.11
  - bzip2=1.0.8
  - gzip=1.10
  - zip=3.0
  - pigz=2.6
  - unzip=6.0
  - grep=3.4
  - gawk=5.1.0
