name: pgas
dependencies:
  - Python=3.8.*
  - pip
  - openssl
  - Snakemake=7.24.2
  - tabulate=0.9.0
  - pyyaml=6.0
  - pandas=1.4.*
  - pytables=3.6.*
  - intervaltree=3.0.2
  - pulp=2.7.0
  - coincbc=2.10.8
  - mamba=1.3.1