name: ashleys
dependencies:
 - python=3.7.*
 - joblib=0.16.0
 - pip=20.2.3
 - scikit-learn=0.23.2
 - scipy=1.5.2
 - pandas=1.1.2
 - setuptools=49.6.0
 - numpy=1.19.1
 - pysam=0.16.0.1
 - matplotlib=3.2.1
 - pytest=6.2.2
