name: dipassm
channels:
  - conda-forge
  - bioconda
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - openssl=1.0.2t
  - Snakemake=5.10.0
  - drmaa=0.7.9
  - pyyaml=5.3
  - pandas=1.0.5
  - pytables=3.6.1
  - intervaltree=3.0.2