name: whatshap
channels:
  - conda-forge
  - bioconda
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - libdeflate=1.3  # v1.0 may trigger pysam import error - DO NOT DOWNGRADE
  - bcftools=1.9  # part of the env for joint stats computation rules
  - pysam=0.15.3
  - pigz=2.4
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - curl=7.64.0
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - krb5=1.16.3
  - ld_impl_linux-64=2.33.1
  - ldc=1.13.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libssh2=1.8.0
  - libstdcxx-ng=9.1.0
  - make=4.2.1
  - ncurses=6.2
  - openssl=1.0.2t
  - readline=7.0
  - setuptools=49.2.1
  - sqlite=3.28.0
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - biopython=1.76
  - numpy=1.17.1
  - networkx=2.4
  - pyfaidx=0.5.9.1
  - decorator=4.4.2
  - six=1.15.0
  - pip:
    - git+https://bitbucket.org/whatshap/whatshap@a3f8c91
