name: pgas
dependencies:
  - Python=3.8.*
  - pip
  - openssl
  - Snakemake=7.6.2
  - tabulate=0.8.10
  - pyyaml=5.3
  - pandas=1.4.*
  - pytables=3.6.*
  - intervaltree=3.0.2
  - pulp=2.6.*
  - coincbc=2.10.*
  - mamba=0.23.*