# Default runtime profile for deNBI Tuebingen infrastructure / PBS-TORQUE cluster

cluster: >-
  qsub
  -d ../run_folder
  -l walltime={cluster.run_hrs}:{cluster.run_min}:00,nodes=1:ppn={cluster.cores},mem={cluster.mem_mb}M
  -N {cluster.name} -o {cluster.output} -e {cluster.error}
cluster-config: environment/snakemake/cluster/denbi_tu_pbs/denbi_cluster.json
local-cores: 2
jobs: 40
latency-wait: 300
keep-going: True
rerun-incomplete: True
keep-incomplete: False
restart-times: 1
use-conda: True
conda-frontend: mamba
conda-prefix: /beeond/projects/conda_envs
use-envmodules: False
nolock: True
max-status-checks-per-second: 0.01
default-resources:
  - runtime_hrs=1
  - runtime_min=59
  - mem_per_cpu_mb=2048
  - mem_total_mb=4096