
cores: 4
latency-wait: 5
keep-going: True
rerun-incomplete: True
keep-incomplete: True
restart-times: 0
use-conda: True
conda-frontend: mamba
conda-prefix: /home/local/software/conda/envs/
use-envmodules: False
nolock: False
resources:
  mem_total_mb=14336
default-resources:
  - mem_per_cpu_mb=1024
  - mem_total_mb=1024
  - runtime_hrs=1
  - runtime_min=59
#forcerun: "config.dump"
